Codereview
radoshDev/Front-end_School_HW_1 pull request #1
Opened 2021-12-20 14:17 UTC by radoshDev

2021-12-20 18:34 UTC, KotenkoNata reviewed
Все ок. Не смогла проверить TypeScript.

2021-12-20 18:34 UTC, KotenkoNata commented on src/components/Trends/index.tsx
> +	}, [dispatch, currentPage, data.length])
Если data будет `undefined`, тогда `data.length` вызовет ошибку.

```suggestion
	}, [currentPage, data])
```

2021-12-20 18:34 UTC, KotenkoNata commented on src/components/UI/ErrorText.tsx
> +
Я видела что в других файлах используется Props. Возможно нужно и тут добавить?

2021-12-20 18:34 UTC, KotenkoNata commented on src/components/User/VideoBlock.tsx
> +				data?.map?.(item => <VideoItem videoInfo={item} key={item.id} />)
Зачем проверяешь map y data? Data может быть не массивом?

2021-12-20 18:34 UTC, KotenkoNata commented on src/features/user/userAPI.ts
> +		return response.data.user
Много повторяющегося кода. Как пример, я сделала вот так:

```js
import axios from "axios";

const API_KEY = process.env.REACT_APP_API_KEY;
const BASE_URL = "https://tiktok33.p.rapidapi.com";

const options = {
  method: "GET",
  url: `${BASE_URL}`,
  headers: {
    "x-rapidapi-host": "tiktok33.p.rapidapi.com",
    "x-rapidapi-key": `${API_KEY}`,
  },
};

export function fetchTrendingVideo() {
  const newOptions = {
    ...options,
    url: `${BASE_URL}/trending/feed`,
  };
  return axios.get(newOptions.url, newOptions);
}

export function getUserDetails(name) {
  const newOptions = {
    ...options,
    url: `${BASE_URL}/user/info/${name}`,
  };
  return axios.get(newOptions.url, newOptions);
}

```

2021-12-20 21:27 UTC, radoshDev commented on .env
> +REACT_APP_API_KEY_MAIN = "c1257dc04cmshd888bbb072eb770p1f2b8ajsnbf16d4cd1d66"
Справедливо підмічено. Виправлю

2021-12-21 13:55 UTC, radoshDev commented on .gitignore
> +.env.local
Я перейменував на файл .env.local

2021-12-21 16:55 UTC, radoshDev commented on src/components/Trends/Content.tsx
> +}
Так в TypeScript типізуються вхідні пропси для копонета. Чи що ти маєш на увазі?

2021-12-21 20:20 UTC, KotenkoNata commented on src/components/Trends/Content.tsx
> +}
Я вижу, что ты где-то ты используешь пропсы, где-то нет. Насколько мне известно TypeScript имеет свои типы-классы. Не думала что нужны пропсы.

2021-12-22 08:52 UTC, radoshDev commented on src/components/UI/ErrorText.tsx
> +
Тут не потрібно описувати типізацію для props, оскільки очікується отримання тільки children (FC типізує це)

2021-12-22 09:01 UTC, radoshDev commented on src/components/Trends/Content.tsx
> +}
Де я компонент отримує пропси в параметрах, там я їх описував, де тільки children то використовував FC що імпортується з React. Якщо взагалі немає пропсів, то не описував, бо нема потреби. Наведи приклад, щоб я розумів про які типи-класи йде мова.

2021-12-22 09:02 UTC, radoshDev commented on package.json
> +		"prettier": "^2.5.1"
Додав в новому комміті. Дякую)

2021-12-22 09:14 UTC, radoshDev commented on src/components/Trends/TrendVideo.tsx
> +	}, [inView, isLoading])
В даній ситуації потрібно, тому що при зміні стану змінної **inView**  треба зробити ререндер компоненти і викликати функцію **handleAutoPlay**

2021-12-22 09:36 UTC, radoshDev commented on src/components/Trends/index.tsx
> +	}, [dispatch, currentPage, data.length])
`data` в redux store по замовчуванню вказано як порожній масив, тому `length `завжди буде. A `dispatch` сам eslint реакта рекомендує вносити

2021-12-22 09:51 UTC, radoshDev commented on src/components/User/VideoBlock.tsx
> +				data?.map?.(item => <VideoItem videoInfo={item} key={item.id} />)
Ага, дякую

2021-12-22 09:53 UTC, radoshDev commented on src/features/user/userAPI.ts
> +		return response.data.user
Так, треба переробити, дякую

2021-12-23 16:15 UTC, VolodymyrSi requested changes
Дякую вам webstorm і intellisense, що не дали втонути в синтаксисі тайпскрипта з редаксом :)

2021-12-23 16:15 UTC, VolodymyrSi commented on src/components/UI/Video.tsx
> +		if (videoRef.current.muted) {
можливо тут можна переписати через guard clause щоб обійтись if-ами без else, і це акуратніше виглядатиме?

2021-12-23 16:15 UTC, VolodymyrSi commented on src/components/User/index.tsx
> +			<StatsInfo loading={infoLoading} data={infoData.stats} />
як щодо isInfoLoading?

2021-12-23 16:15 UTC, VolodymyrSi commented on src/features/user/userSlice.ts
> +		isLoading: true,
трошки не розумію, чому початковий стан всюди true.
Я бачу це так:

**початково:**

_isLoading - false._

**Просимо якісь дані**

GetSomeData() {
isLoading: true;
fetch data()
success/fail -> isLoading -> false

тобто isLoading не є true, поки не почнеться якийсь запит.

якщо це `hasData` -> він false початково, і аж до тієї точки, поки не будуть отримані дані

2021-12-23 16:15 UTC, VolodymyrSi commented on src/types/usersTypes.ts
> +export type User = {
Боже, скільки роботи в тайпскрипті :)

2021-12-23 20:56 UTC, KotenkoNata requested changes
Крутий код, мені сподобався :)
Чекаю коли видалиться `.env` і тисну Approve :)

2021-12-23 20:56 UTC, KotenkoNata commented on src/components/Trends/TrendVideo.tsx
> +	}, [inView, isLoading])
Ок, просто з цього коду було не зрозуміти, що там є змінна, яка використовуюється набагато вище :)

Тоді все ок, резолвлю цей комент.

PS: Хоча можна посунути чи функції ближче, або створити кастомний хук, але це не обов'язково :)

2021-12-23 20:56 UTC, KotenkoNata commented on src/components/Trends/Content.tsx
> +}
Ок, зрозуміло, тоді все ок :)

2021-12-23 20:56 UTC, KotenkoNata commented on .eslintrc.json
> +	"plugins": ["react", "@typescript-eslint", "prettier"],
Ще був плагін `unicorn`

2021-12-23 20:56 UTC, KotenkoNata commented on .eslintrc.json
> +		"react/require-default-props": "off"
Якось мало рулів для лінта. Мені здавалось що треба більше. Чи то так ок?

2021-12-27 14:19 UTC, radoshDev commented on src/features/user/userSlice.ts
> +		isLoading: true,
Це для перших мілісекунд завантаження програми, щоб рендерився Preloader, поки не отримаємо дані від сервера.

2021-12-27 15:17 UTC, radoshDev commented on src/components/User/index.tsx
> +			<StatsInfo loading={infoLoading} data={infoData.stats} />
Виправив в новому коміті

2021-12-27 15:27 UTC, radoshDev commented on src/components/UI/ItemActionBar.tsx
> +				<span className="amount">{kFormatter(likeCount)}</span>
Це ж не жаргон, це стандарт що означає **kilo**, кілобайт, кілограм...

2021-12-27 15:39 UTC, radoshDev commented on src/components/UI/Video.tsx
> +		if (videoRef.current.muted) {
Я вважаю що вистачить одного guard clause на початку.

2021-12-27 16:42 UTC, radoshDev commented on .eslintrc.json
> +	"plugins": ["react", "@typescript-eslint", "prettier"],
Виправив

2021-12-27 16:44 UTC, radoshDev commented on src/components/Nav.tsx
> +						TikTuk
Кращого рішення не бачу)

2021-12-27 17:10 UTC, KotenkoNata approved these changes

2021-12-30 19:28 UTC, merged

2022-01-05 10:27 UTC, MiKolka7 commented
Рекомендую переглянути ще правила для TS
```
'@typescript-eslint/no-inferrable-types': [2],
'@typescript-eslint/no-explicit-any': 2,
// для форматування в єдиному стилі
'@typescript-eslint/member-delimiter-style': [2, {
        delimiter: 'none',
        requireLast: true,
    },
    singleline: {
        delimiter: 'comma',
        requireLast: false,
    },
}],
'@typescript-eslint/prefer-ts-expect-error': 2,
'@typescript-eslint/explicit-function-return-type': [2, { allowExpressions: true }],
'@typescript-eslint/no-floating-promises': 2,
```

2022-01-05 10:29 UTC, MiKolka7 commented
Дуже хороші матеріали про ts config https://habr.com/ru/post/542234/ а особливо частину про строгість https://habr.com/ru/post/557738/. Рекомендую почитати та доналаштувати проект. Без відповідно налаштованого TS з нього мало вихлопу.

2022-01-05 10:30 UTC, MiKolka7 commented
![image](https://user-images.githubusercontent.com/4210802/148202692-7efb0148-aeb5-477a-ab03-329941ec5bae.png)
JetBrains IDE можуть автоматично генерувати типи по тому що використовується у функції

2022-01-05 10:44 UTC, MiKolka7 reviewed
Чудова робота

2022-01-05 10:44 UTC, MiKolka7 commented on src/utils/kFormatter.ts
> +export const kFormatter = (count: number): string | number => {
Складна назва, поки в код не заглянеш не зрозумієш, що робить ця функція. Можливо щось типу abbreviateNumber краще б підійшло.

2022-01-05 10:44 UTC, MiKolka7 commented on src/components/User/VideoItem.tsx
> +type Props = {
Чудово що для даних використовуєш типи.

2022-01-05 10:52 UTC, MiKolka7 commented on src/components/Nav.tsx
> +		border-bottom: 1px solid grey;
Алфавітний порядок поганий підхід, так пробували писати, ні до чого хорошого не привело. На практиці використовується те що @VolodymyrSi описав. В ручному варіанті робити сенсу не має, тому що в кожної людини свій порядок, а як показує практика між собою люди погано домовляються.
Тому для таких речей використовують https://www.npmjs.com/package/stylelint-order